package robhancdklibawsgrafana

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
	_init_ "github.com/robert-hanuschke/robhan-cdk-lib-aws-grafana/robhancdklibawsgrafana/jsii"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/robert-hanuschke/robhan-cdk-lib-aws-grafana/robhancdklibawsgrafana/internal"
)

type WorkspaceBase interface {
	awscdk.Resource
	IWorkspace
	// The account access type for the workspace.
	// Default: - not available on workspaces imported from an ARN via `Workspace.fromWorkspaceArn`
	//
	AccountAccessType() AccountAccessType
	// The authentication providers for the workspace.
	// Default: - not available on workspaces imported from an ARN via `Workspace.fromWorkspaceArn`
	//
	AuthenticationProviders() *[]AuthenticationProviders
	// The client token for the workspace.
	// Default: - not available on imported workspaces.
	//
	ClientToken() *string
	// The date that the workspace was created.
	// Default: - not available on imported workspaces.
	//
	CreationTimestamp() *string
	// The data sources of this workspace.
	// Default: - no data sources.
	//
	DataSources() *[]*string
	// The description of this workspace.
	// Default: - no description.
	//
	Description() *string
	// The URL that users can use to access the Grafana console in the workspace.
	// Default: - not available on imported workspaces.
	//
	Endpoint() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	Env() *interfaces.ResourceEnvironment
	// Specifies the version of Grafana supported by this workspace.
	// Default: - not available on imported workspaces.
	//
	GrafanaVersion() *string
	// The most recent date that the workspace was modified.
	// Default: - not available on imported workspaces.
	//
	ModificationTimestamp() *string
	// The name of this workspace.
	// Default: - a name is generated by CloudFormation.
	//
	Name() *string
	// The configuration settings for network access to your workspace.
	// Default: - no network access control, the workspace is open to all traffic.
	//
	NetworkAccessControl() *NetworkAccessControl
	// The tree node.
	Node() constructs.Node
	// The notification destinations for the workspace.
	// Default: - no notification destinations.
	//
	NotificationDestinations() *[]NotificationDestinations
	// Specifies the organizational units that this workspace is allowed to use data sources from, if this workspace is in an account that is part of an organization.
	// Default: - no organizational units.
	//
	OrganizationalUnits() *[]*string
	// The name of the IAM role that is used to access resources through Organizations.
	// Default: - no organization role name.
	//
	OrganizationRoleName() *string
	// The permission type for the workspace.
	// Default: - not available on workspaces imported from an ARN via `Workspace.fromWorkspaceArn`
	//
	PermissionType() PermissionTypes
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// Whether plugin administration is enabled in the workspace.
	//
	// Setting to true allows workspace
	// admins to install, uninstall, and update plugins from within the Grafana workspace.
	//
	// This option is only valid for workspaces that support Grafana version 9 or newer.
	// Default: - false.
	//
	PluginAdminEnabled() *bool
	// The IAM role that grants permissions to the AWS resources that the workspace will view data from.
	// Default: - no role is attached.
	//
	Role() awsiam.IRole
	// If the workspace uses SAML, use this structure to map SAML assertion attributes to workspace user information and define which groups in the assertion attribute are to have the Admin and Editor roles in the workspace.
	// Default: - no SAML configuration.
	//
	SamlConfiguration() *SamlConfiguration
	// Specifies whether the workspace's SAML configuration is complete.
	// Default: - not available on imported workspaces.
	//
	SamlConfigurationStatus() *string
	// The ID of the IAM Identity Center-managed application that is created by Amazon Managed Grafana.
	// Default: - not available on imported workspaces.
	//
	SsoClientId() *string
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// The name of the AWS CloudFormation stack set that is used to generate IAM roles to be used for this workspace.
	// Default: - no stack set name.
	//
	StackSetName() *string
	// The current status of the workspace.
	// Default: - not available on imported workspaces.
	//
	Status() *string
	// The configuration settings for an Amazon VPC that contains data sources for your Grafana workspace to connect to.
	// Default: - no VPC connection.
	//
	VpcConfiguration() *VpcConfiguration
	// The ARN of this workspace.
	WorkspaceArn() *string
	// The unique ID of this workspace.
	WorkspaceId() *string
	// Override the cross-stack reference strength for this resource.
	//
	// When set, any cross-stack reference to this resource will use the specified
	// mechanism instead of the global default determined by the
	// `@aws-cdk/core:defaultCrossStackReferences` context key. This is useful for
	// selectively weakening specific references to avoid the "deadly embrace" problem
	// without changing the app-wide default.
	ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	GetWorkspaceArn(workspaceId *string) *string
	GetWorkspaceId(workspaceArn *string) *string
	// Returns a string representation of this construct.
	ToString() *string
	// Applies one or more mixins to this construct.
	//
	// Mixins are applied in order. The list of constructs is captured at the
	// start of the call, so constructs added by a mixin will not be visited.
	// Use multiple `with()` calls if subsequent mixins should apply to added
	// constructs.
	With(mixins ...constructs.IMixin) constructs.IConstruct
}

// The jsii proxy struct for WorkspaceBase
type jsiiProxy_WorkspaceBase struct {
	internal.Type__awscdkResource
	jsiiProxy_IWorkspace
}

func (j *jsiiProxy_WorkspaceBase) AccountAccessType() AccountAccessType {
	var returns AccountAccessType
	_jsii_.Get(
		j,
		"accountAccessType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) AuthenticationProviders() *[]AuthenticationProviders {
	var returns *[]AuthenticationProviders
	_jsii_.Get(
		j,
		"authenticationProviders",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) ClientToken() *string {
	var returns *string
	_jsii_.Get(
		j,
		"clientToken",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) CreationTimestamp() *string {
	var returns *string
	_jsii_.Get(
		j,
		"creationTimestamp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) DataSources() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"dataSources",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Description() *string {
	var returns *string
	_jsii_.Get(
		j,
		"description",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Endpoint() *string {
	var returns *string
	_jsii_.Get(
		j,
		"endpoint",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) GrafanaVersion() *string {
	var returns *string
	_jsii_.Get(
		j,
		"grafanaVersion",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) ModificationTimestamp() *string {
	var returns *string
	_jsii_.Get(
		j,
		"modificationTimestamp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Name() *string {
	var returns *string
	_jsii_.Get(
		j,
		"name",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) NetworkAccessControl() *NetworkAccessControl {
	var returns *NetworkAccessControl
	_jsii_.Get(
		j,
		"networkAccessControl",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) NotificationDestinations() *[]NotificationDestinations {
	var returns *[]NotificationDestinations
	_jsii_.Get(
		j,
		"notificationDestinations",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) OrganizationalUnits() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"organizationalUnits",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) OrganizationRoleName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"organizationRoleName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) PermissionType() PermissionTypes {
	var returns PermissionTypes
	_jsii_.Get(
		j,
		"permissionType",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) PluginAdminEnabled() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"pluginAdminEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Role() awsiam.IRole {
	var returns awsiam.IRole
	_jsii_.Get(
		j,
		"role",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) SamlConfiguration() *SamlConfiguration {
	var returns *SamlConfiguration
	_jsii_.Get(
		j,
		"samlConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) SamlConfigurationStatus() *string {
	var returns *string
	_jsii_.Get(
		j,
		"samlConfigurationStatus",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) SsoClientId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"ssoClientId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) StackSetName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"stackSetName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) Status() *string {
	var returns *string
	_jsii_.Get(
		j,
		"status",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) VpcConfiguration() *VpcConfiguration {
	var returns *VpcConfiguration
	_jsii_.Get(
		j,
		"vpcConfiguration",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) WorkspaceArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workspaceArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkspaceBase) WorkspaceId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workspaceId",
		&returns,
	)
	return returns
}


func NewWorkspaceBase_Override(w WorkspaceBase, scope constructs.Construct, id *string, props *awscdk.ResourceProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@robhan-cdk-lib/aws_grafana.WorkspaceBase",
		[]interface{}{scope, id, props},
		w,
	)
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
func WorkspaceBase_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateWorkspaceBase_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_grafana.WorkspaceBase",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func WorkspaceBase_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWorkspaceBase_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_grafana.WorkspaceBase",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func WorkspaceBase_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWorkspaceBase_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@robhan-cdk-lib/aws_grafana.WorkspaceBase",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkspaceBase) ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength) {
	if err := w.validateApplyCrossStackReferenceStrengthParameters(strength); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"applyCrossStackReferenceStrength",
		[]interface{}{strength},
	)
}

func (w *jsiiProxy_WorkspaceBase) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := w.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (w *jsiiProxy_WorkspaceBase) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkspaceBase) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := w.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkspaceBase) GetResourceNameAttribute(nameAttr *string) *string {
	if err := w.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkspaceBase) GetWorkspaceArn(workspaceId *string) *string {
	if err := w.validateGetWorkspaceArnParameters(workspaceId); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getWorkspaceArn",
		[]interface{}{workspaceId},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkspaceBase) GetWorkspaceId(workspaceArn *string) *string {
	if err := w.validateGetWorkspaceIdParameters(workspaceArn); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getWorkspaceId",
		[]interface{}{workspaceArn},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkspaceBase) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkspaceBase) With(mixins ...constructs.IMixin) constructs.IConstruct {
	args := []interface{}{}
	for _, a := range mixins {
		args = append(args, a)
	}

	var returns constructs.IConstruct

	_jsii_.Invoke(
		w,
		"with",
		args,
		&returns,
	)

	return returns
}

